import { openDb } from "../configDB";

// Função de criação do banco e insert de alguns registros básicos (usuário e jogos).
export async function criaDatabase(){
    openDb().then(db => {
        // O script foi gerado pelo MySQL workbench, mas a sintaxe, neste caso, não apresentou conflito
        // com a do SQLite, podendo também ser aplicada a ele
        var scriptCriacao = `
        -- MySQL Script generated by MySQL Workbench
        -- Sun Jun 23 15:50:41 2024
        -- Model: New Model    Version: 1.0
        -- MySQL Workbench Forward Engineering

        SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
        SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
        SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

        -- -----------------------------------------------------
        -- Schema mydb
        -- -----------------------------------------------------

        -- -----------------------------------------------------
        -- Schema mydb
        -- -----------------------------------------------------
        CREATE SCHEMA IF NOT EXISTS 'mydb' DEFAULT CHARACTER SET utf8 ;
        USE 'mydb' ;

        -- -----------------------------------------------------
        -- Table 'mydb'.'Conta'
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS 'mydb'.'Conta' (
        'nome_usuario' VARCHAR(45) NOT NULL,
        'senha' VARCHAR(45) NOT NULL,
        'nome' VARCHAR(45) NOT NULL,
        'Id_conta' INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY ('Id_conta'))
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table 'mydb'.'Jogo'
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS 'mydb'.'Jogo' (
        'nome_jogo' VARCHAR(45) NOT NULL,
        'Id_jogo' INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY ('Id_jogo'))
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table 'mydb'.'Partidas'
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS 'mydb'.'Partidas' (
        'Id_partida' INT NOT NULL AUTO_INCREMENT,
        'Id_jogo' INT NOT NULL,
        'Id_conta_1' INT NOT NULL,
        'Id_conta_2' INT NOT NULL,
        'pontuacao' INT NOT NULL,
        PRIMARY KEY ('Id_partida'),
        INDEX 'Id_conta_1_idx' ('Id_conta_1' ASC) INVISIBLE,
        INDEX 'Id_conta_2_idx' ('Id_conta_2' ASC) VISIBLE,
        INDEX 'Id_jogo_idx' ('Id_jogo' ASC) VISIBLE,
        CONSTRAINT 'Id_conta_1_Partidas'
            FOREIGN KEY ('Id_conta_1')
            REFERENCES 'mydb'.'Conta' ('Id_conta')
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
        CONSTRAINT 'Id_conta_2_Partidas'
            FOREIGN KEY ('Id_conta_2')
            REFERENCES 'mydb'.'Conta' ('Id_conta')
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
        CONSTRAINT 'Id_jogo_Partidas'
            FOREIGN KEY ('Id_jogo')
            REFERENCES 'mydb'.'Jogo' ('Id_jogo')
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table 'mydb'.'Pontuacao'
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS 'mydb'.'Pontuacao' (
        'Id_jogo' INT NOT NULL,
        'Id_conta' INT NOT NULL,
        'single_player' BINARY(1) NOT NULL,
        'pontuacao' INT NOT NULL,
        'Id_Pontuacao' INT NOT NULL AUTO_INCREMENT,
        INDEX 'Id_conta_idx' ('Id_conta' ASC) VISIBLE,
        PRIMARY KEY ('Id_Pontuacao'),
        CONSTRAINT 'Id_conta_Pontuacao'
            FOREIGN KEY ('Id_conta')
            REFERENCES 'mydb'.'Conta' ('Id_conta')
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
        CONSTRAINT 'Id_jogo_Pontuacao'
            FOREIGN KEY ('Id_jogo')
            REFERENCES 'mydb'.'Jogo' ('Id_jogo')
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
        ENGINE = InnoDB;


        SET SQL_MODE=@OLD_SQL_MODE;
        SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
        SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

        -- -----------------------------------------------------
        -- Data for table 'mydb'.'Conta'
        -- -----------------------------------------------------
        START TRANSACTION;
        USE 'mydb';
        INSERT OR REPLACE INTO 'mydb'.'Conta' ('nome_usuario', 'senha', 'nome', 'Id_conta') VALUES ('admin', '123', 'Admin', 1);

        COMMIT;


        -- -----------------------------------------------------
        -- Data for table 'mydb'.'Jogo'
        -- -----------------------------------------------------
        START TRANSACTION;
        USE 'mydb';
        INSERT OR REPLACE INTO 'mydb'.'Jogo' ('nome_jogo', 'Id_jogo') VALUES ('Jogo da Velha', 1);
        INSERT OR REPLACE INTO 'mydb'.'Jogo' ('nome_jogo', 'Id_jogo') VALUES ('Campo Minado', 2);
        INSERT OR REPLACE INTO 'mydb'.'Jogo' ('nome_jogo', 'Id_jogo') VALUES ('Dama', 3);

        COMMIT;
        `;

        db.exec(scriptCriacao);
    });
}